---
version: "2.1"
services:
  lidarr:
    image: linuxserver/lidarr:latest
    container_name: Deployed_lidarr
    environment:
      - TZ=America/New_York
    volumes:
      - ${LIDARR_HOST_CONFIG_PATH}:/config
      - ${LIDARR_HOST_MUSIC_MEDIA_PATH}:/music #optional
      - ${LIDARR_HOST_DOWNLOADS_PATH}:/downloads #optional
    ports:
      - 8686:8686
    restart: unless-stopped
  
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: Deployed_sonarr
    environment:
      - TZ=America/New_York
    volumes:
      - ${SONARR_HOST_CONFIG_PATH}:/config
      - ${SONARR_HOST_TV_MEDIA_PATH}:/tv #optional
      - ${SONARR_HOST_DOWNLOADS_PATH}:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped
  
  radarr:
    image: linuxserver/radarr:latest
    container_name: Deployed_radarr
    environment:
      - TZ=America/New_York
    volumes:
      - ${RADARR_HOST_CONFIG_PATH}:/config
      - ${RADARR_HOST_MOVIE_MEDIA_PATH}:/movies #optional
      - ${RADARR_HOST_DOWNLOADS_PATH}:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped

  lazylibrarian:
    image: linuxserver/lazylibrarian:latest
    container_name: Deployed_lazylibrarian
    environment:
      - TZ=America/New_York
      - DOCKER_MODS=linuxserver/calibre-web:calibre|linuxserver/mods:lazylibrarian-ffmpeg #optional
    volumes:
      - ${LAZYLIBRARIAN_HOST_CONFIG_PATH}:/config
      - ${LAZYLIBRARIAN_HOST_DOWNLOADS_PATH}:/downloads
      - ${LAZYLIBRARIAN_HOST_EBOOKS_PATH}:/books #optional
    ports:
      - 5299:5299
    restart: unless-stopped

  prowlarr:
    image: linuxserver/prowlarr:develop
    container_name: Deployed_prowlarr
    environment:
      - TZ=America/New_York
    volumes:
      - ${PROWLARR_HOST_CONFIG_PATH}:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  overseerr:
    image: linuxserver/overseerr:latest
    container_name: Deployed_overseerr
    environment:
      - TZ=America/New_York
    volumes:
      - ${OVERSEERR_HOST_CONFIG_PATH}:/config
    ports:
      - 5055:5055
    restart: unless-stopped
    
  deluge:
    image: linuxserver/deluge:latest
    container_name: Deployed_deluge
    environment:
      - TZ=America/New_York
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - ${DELUGE_HOST_CONFIG_PATH}:/config
      - ${DELUGE_HOST_DOWNLOADS_PATH}:/downloads
      - ${DELUGE_HOST_COMPLETED_PATH}:/completed
      - ${DELUGE_HOST_TORRENTFILES_PATH}:/TorrentFiles
    ports:
      - 8112:8112
      - 6881:6881
      - 6881:6881/udp
      - 58846:58846
    restart: unless-stopped